import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { renderSizeBadges } from './badge.js'
import type { CacheMeta, SizeReport } from './types.js'

export type WriteCacheResult = {
  readonly skipped: boolean
  readonly versionPath: string
  readonly latestBadgePath: string
  readonly wroteLatest: boolean
}

const readJsonIfExists = async <T>(filePath: string): Promise<T | null> => {
  try {
    const raw = await readFile(filePath, 'utf8')
    return JSON.parse(raw) as T
  } catch {
    return null
  }
}

const sortVersions = (versions: readonly string[]): string[] =>
  [...versions].sort((a, b) => a.localeCompare(b, undefined, { numeric: true }))

/**
 * Pure-ish filesystem write of version history + SVG badges.
 * No git. Safe to unit/smoke test locally.
 */
export const writeCacheArtifacts = async (options: {
  readonly cacheDir: string
  readonly report: SizeReport
  readonly updateLatestOnPrerelease: boolean
}): Promise<WriteCacheResult> => {
  const latestBadgePath = 'badges/latest.svg'
  const versionPath = path.join(
    options.cacheDir,
    'versions',
    `${options.report.version}.json`,
  )

  const existing = await readJsonIfExists<SizeReport>(versionPath)
  if (existing) {
    return {
      skipped: true,
      versionPath: path.relative(options.cacheDir, versionPath),
      latestBadgePath,
      wroteLatest: false,
    }
  }

  await mkdir(path.join(options.cacheDir, 'versions'), { recursive: true })
  await mkdir(path.join(options.cacheDir, 'badges'), { recursive: true })

  await writeFile(versionPath, `${JSON.stringify(options.report, null, 2)}\n`)

  const badges = renderSizeBadges(options.report)
  const shouldUpdateLatest =
    !options.report.prerelease || options.updateLatestOnPrerelease

  if (shouldUpdateLatest) {
    await writeFile(path.join(options.cacheDir, latestBadgePath), badges.latest)
    await writeFile(path.join(options.cacheDir, 'badges/gzip.svg'), badges.gzip)
    await writeFile(
      path.join(options.cacheDir, 'badges/brotli.svg'),
      badges.brotli,
    )
    await writeFile(path.join(options.cacheDir, 'badges/minified.svg'), badges.raw)
  }

  await writeFile(
    path.join(options.cacheDir, 'badges', `${options.report.version}.svg`),
    badges.gzip,
  )

  const metaPath = path.join(options.cacheDir, 'meta.json')
  const previousMeta = await readJsonIfExists<CacheMeta>(metaPath)
  const versions = sortVersions([
    ...(previousMeta?.versions ?? []),
    options.report.version,
  ])

  const meta: CacheMeta = {
    schemaVersion: 1,
    packageName: options.report.name,
    updatedAt: options.report.measuredAt,
    versions,
  }

  await writeFile(metaPath, `${JSON.stringify(meta, null, 2)}\n`)
  await writeFile(
    path.join(options.cacheDir, 'README.md'),
    `# package-size-cache

Append-only size history for \`${options.report.name}\`.

- Latest badge: [\`badges/latest.svg\`](./badges/latest.svg)
- Versions: [\`versions/\`](./versions/)

Generated by **Package Size Badge** action. Do not edit by hand.
`,
  )

  return {
    skipped: false,
    versionPath: path.relative(options.cacheDir, versionPath),
    latestBadgePath,
    wroteLatest: shouldUpdateLatest,
  }
}
